### ISSUE TITLE
Set up Flask

### ISSUE THREAD

**Issue by nathan815** [seeus-dev/seeus-backend#1]
Set up Flask web server. Configure a basic route.

**Comment by nathan815** [comment]
@Mazawrath I just changed this ticket from express to flask.

**Comment by Mazawrath** [comment]
Currently in progress. I am setting up the VM right now.

**Comment by nathan815** [comment]
@Mazawrath Cool. This was more intended to be about setting up the code for flask. Created #5 for setting up VM.
