### ISSUE TITLE
Design database schema

### ISSUE THREAD

**Issue by nathan815** [seeus-dev/seeus-backend#4]
Tables:

- users
- staff (dispatchers, supervisors, admin [Torres])
- requests
- locations
- config (hours, dispatcher toggles, etc.)

Implementation: MySQL or PostgreSQL. A benefit of PostgreSQL is it has query support for lat/long coordinates using [PostGIS](https://postgis.net/).

**Comment by Mazawrath** [comment]
Completed in [lucidchart](https://www.lucidchart.com/invitations/accept/77446dc0-64fb-4ab9-b584-22b5cdc96b97)
