### ISSUE TITLE
Create a list of EMU locations for SEEUS

### ISSUE THREAD

**Issue by nathan815** [seeus-dev/seeus-backend#7]
I did some digging into EMU's [online campus map](https://www.emich.edu/map/index.php) and found they have an endpoint that returns a JSON array of every map item:

https://ic.emich.edu/api/external/mapitems

We can extract the campus buildings, parking lots, etc. - basically anything that SEEUS would escort people from/to. Would be nice to make a python script that populates the relevant locations from this JSON into postgresql db `locations` table. (DB schema see #4)

**Comment by Mazawrath** [comment]
I believe this better belongs in the dispatcher as they will manually add the locations.

**Comment by nathan815** [comment]
The dispatcher UI will have an area for adding/updating locations but I think we should prepopulate the locations DB table from EMU's map data, since we have this available to us. And we need the locations there for the app to work.
